### ISSUE TITLE
I have got this issue

### ISSUE THREAD

**Issue by fmoghaddampoor** [Webreaper/CentralisedPackageConverter#28]
Startup exception: System.Xml.XmlException: The 'Reference' start tag on line 41 position 6 does not match the end tag of 'ItemGroup'. Line 55, position 5.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at CentralisedPackageConverter.PackageConverter.ConvertProject(FileInfo csprojFile, Boolean dryRun, Encoding encoding, String lineWrap) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.cs:line 269
   at CentralisedPackageConverter.PackageConverter.<>c__DisplayClass3_0.<ProcessConversion>b__5(FileInfo proj) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.cs:line 77
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CentralisedPackageConverter.PackageConverter.ProcessConversion(CommandLineOptions o) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.cs:line 77
   at Program.<>c.<<Main>$>b__0_0(CommandLineOptions o) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/Program.cs:line 10
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Program.<Main>$(String[] args) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/Program.cs:line 6

**Comment by Webreaper** [comment]
Sounds like your CSProj is invalid XML. It may be that VS is more resilient to that sort of error. 

If you really think that the csproj is valid and that it's the centralised package manager converter that has a problem, then you'll need to attach the csproj file, as it's impossible to figure out what's wrong without it.
