### ISSUE TITLE
Startup exception: System.InvalidOperationException: Could not find color or style 'MSBuild'.

### ISSUE THREAD

**Issue by frogcrush** [Webreaper/CentralisedPackageConverter#50]
Having a crash when running the .NET tool:

```
Startup exception: System.InvalidOperationException: Could not find color or style 'MSBuild'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 10
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 29
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 77
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, IFormatProvider provider, String format, Object[] args) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 47
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, IFormatProvider provider, String format, Object[] args) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 129
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String format, Object[] args) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 88
   at Spectre.Console.AnsiConsole.MarkupLine(String format, Object[] args) in /_/src/Spectre.Console/AnsiConsole.Markup.cs:line 91
   at CentralisedPackageConverter.Output.InfoLine(String message, Object[] args) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/OutputExtensions.cs:line 11
   at CentralisedPackageConverter.PackageConverter.ConvertProject(FileInfo projectFile, Boolean dryRun, Encoding encoding, String lineWrap, Versioning versioning) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.cs:line 406
   at CentralisedPackageConverter.PackageConverter.<>c__DisplayClass3_0.<ProcessConversion>b__4(FileInfo proj) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.cs:line 95
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CentralisedPackageConverter.PackageConverter.ProcessConversion(CommandLineOptions o) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.cs:line 95
   at Program.<>c.<<Main>$>b__0_0(CommandLineOptions o) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/Program.cs:line 10
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Program.<Main>$(String[] args) in /home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/Program.cs:line 6
   ```

Version:
```
> central-pkg-converter --version
CentralisedPackageConverter 1.0.65+26b51500a7eb8414d0fe939a6b31e4b6704baeac
```

**Comment by frogcrush** [comment]
Changing this line:
```
public static void InfoLine(string message, params object[] args) => AnsiConsole.MarkupLine(message, args);
```

to this:

```
public static void InfoLine(string message, params object[] args) => AnsiConsole.WriteLine(message, args);
```

fixes the crash.

**Comment by Webreaper** [comment]
Want to submit a PR?
