### ISSUE TITLE
Exception: System.Xml.XmlException: Root element is missing

### ISSUE THREAD

**Issue by Thovenaar** [Webreaper/CentralisedPackageConverter#52]
Running into this issue upon using the tool. I ran it in an administrator terminal with the default settings.

```
Startup exception: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at CentralisedPackageConverter.PackageConverter.ConvertProject(FileInfo projectFile, Boolean dryRun, Encoding
encoding, String lineWrap, Versioning versioning) in
/home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.c
s:line 314
   at CentralisedPackageConverter.PackageConverter.<>c__DisplayClass3_0.<ProcessConversion>b__4(FileInfo proj) in
/home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.c
s:line 95
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CentralisedPackageConverter.PackageConverter.ProcessConversion(CommandLineOptions o) in
/home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/PackageConverter.c
s:line 95
   at Program.<>c.<<Main>$>b__0_0(CommandLineOptions o) in
/home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/Program.cs:line 10
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Program.<Main>$(String[] args) in
/home/runner/work/CentralisedPackageConverter/CentralisedPackageConverter/CentralisedPackageConverter/Program.cs:line 6
```

Any suggestions?

**Comment by Thovenaar** [comment]
I checked out the project locally and ran it, worked fine. You can close the issue if you want.
